common/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import firstapp
import common

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('firstapp.urls')),
    path('', firstapp.views.index, name='index'),  # '/' 에 해당되는 path
    path('common/', include('common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'common.views.page_not_found'
handler500 = 'common.views.internal_server_error'

firstapp/urls.py
from django.urls import path
from . import views

app_name = 'firstapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('post_list', views.post_list, name='post_list'),
    path('post/<int:pk>', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('post/modify/<int:pk>', views.post_modify, name='post_modify'),
    path('post/delete/<int:pk>', views.post_delete, name='post_delete'),
    path('view_stock', views.view_stock, name='view_stock'),
    path('lh_notice', views.lh_notice, name='lh_notice'),
    path('fileupload/', views.fileupload, name="fileupload"),
]

common/models.py
from django.db import models

# Create your models here.

firstapp/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    modified_date = models.DateTimeField(null=True, blank=True)

    def publish(self):
        self.save()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return f'/post/{self.pk}'
        
        
class FileUpload(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=40, null=True)
    imgfile = models.ImageField(null=True, upload_to="", blank=True)
    memo = models.TextField()

    def __str__(self):
        return self.title

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

firstapp/forms.py
from django import forms

from .models import Post, FileUpload

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)
        
        
class FileUploadForm(forms.ModelForm):

    class Meta:
        model = FileUpload
        fields = ('title', 'imgfile', 'memo')

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm
from django.conf import settings

# Create your views here.

def page_not_found(request, exception):
    """
    404 Page not found
    """
    return render(request, 'common/404.html', status=404)

def internal_server_error(request):
    """
    500 Internal Server Error
    """
    return render(request, 'common/500.html', status=500)


def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
    	
        form = UserForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('firstapp:index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

firstapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.utils import timezone
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages
from .models import Post, FileUpload
from .forms import PostForm, FileUploadForm
from .stockapi import findStocks
from .lhapi import findNotices



# Create your views here.

def index(request):
    return render(request, 'firstapp/index.html', {})



def post_list(request):
    # 페이지
    page = request.GET.get('page', '1')
    shownum = request.GET.get('shownum', '5')
    
    # 조회
    posts = Post.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')
    
    # 페이징 처리
    paginator = Paginator(posts, shownum)  # 페이지당 10개씩 보여주기
    posts = paginator.get_page(page)
    return render(request, 'firstapp/post_list.html', {'posts': posts})

@login_required(login_url='/common/login/', redirect_field_name='next') # login시 redirect되는 페이지를 직접 redirect_field_name으로 지정, login.html에서 hidden값으로 next 설정
def post_detail(request, pk):
    post = get_object_or_404(Post,pk=pk) #해당 글이 없으면 404페이지를 보여줌
    #post = Post.objects.get(pk=pk)
    return render(request, 'firstapp/post_detail.html', {'post': post})

@login_required(login_url='/common/login/', redirect_field_name='next')
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('firstapp:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'firstapp/post_edit.html', {'form': form})


@login_required(login_url='/common/login/', redirect_field_name='next')
def post_modify(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('firstapp:post_detail', pk=post.id)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.modified_date = timezone.now()  # 수정일시 저장
            post.save()
            return redirect('firstapp:post_detail', pk=post.id)
    else:
        form = PostForm(instance=post)
    context = {'form': form, 'edit':True}
    messages.error(request, '수정권한이 없습니다')
    return render(request, 'firstapp/post_edit.html', context)


@login_required(login_url='/common/login/', redirect_field_name='next')
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('firstapp:post_detail', pk=post.id)
    post.delete()
    return redirect('firstapp:post_list')
    

def view_stock(request):
    s_data = findStocks(request.GET.get('sname'))
    return render(request, 'firstapp/view_stock.html', {'stocks': s_data})

def lh_notice(request):
    status = request.GET.get('PAN_SS')
    lh_data = findNotices(status)
    return render(request, 'firstapp/lh_notices.html', {'notices': lh_data, 'status':status})


'''
def handle_uploaded_file(f):
    with open('some/file/name.txt', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


def upload_file(request):
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['imgfile'])
            return redirect('fileupload')
    else:
        form = FileUploadForm()
    return render(request, 'firstapp/fileupload.html', {'fileuploadForm': form})
'''


def fileupload(request):
    if request.method == 'POST':
        title = request.POST['title']
        memo = request.POST['memo']
        img = request.FILES["imgfile"]
        fileupload = FileUpload(
            title=title,
            memo=memo,
            imgfile=img,
        )
        fileupload.save()
        return redirect('firstapp:fileupload')
    else:
        fileuploadForm = FileUploadForm()
        return render(request, 'firstapp/fileupload.html', {'fileuploadForm': fileuploadForm})

firstapp/templates/common/login.html
{% extends 'firstapp/base.html' %}
 
{% block content %}
<div class="jumbotron">
  <h2>Please Login:</h2>
  <h3>로그인 해주세요.</h3>
 
  <form action="{% url 'common:login' %}" method="post">
    {% csrf_token %}

      {{ form.as_p }}
    {% include "form_errors.html" %}
      <input type="submit" class="btn btn-primary" value="Login">
      <input type="hidden" name="next" value="{{ request.GET.next }}" />
  </form>
    
  <div class="col-8 text-right">
    <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
  </div>
</div>
{% endblock %}

firstapp/templates/common/signup.html
{% extends 'firstapp/base.html' %}

{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'test' }}" autocomplete="off">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}" autocomplete="off">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}" autocomplete="off">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}" autocomplete="off">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

firstapp/templates/firstapp/base.html
{% load static %}
<html>
    <head>
        <title>supy</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <style>
            @media (max-width: 768px) {
                .container {
                    margin: 0px;
                    width: 100%;
                }
                div {
                    word-break:break-all;
                }
                .card-panel p {
                    text-overflow:ellipsis;
                }
            }
        </style>
    </head>
    <body>
        <div class="container">
        <nav>
            <div class="nav-wrapper">
                <a href="{% url 'firstapp:index' %}" class="brand-logo right">Logo</a>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                <ul id="nav-mobile" class="left hide-on-med-and-down">
                    <li><a href="{% url 'firstapp:index' %}">main</a></li>
                    <li><a href="{% url 'firstapp:post_list' %}">Posts</a></li>
                    <li><a href="{% url 'firstapp:view_stock' %}?sname=카카오">Stocks</a></li>
                    <li><a href="{% url 'firstapp:lh_notice' %}">LH</a></li>
                    {% if user.is_authenticated %}
                    <!--li><a href="">Mypage</a></li-->
                    <li><a href="{% url 'common:logout' %}?next={{ request.path }}">Logout</a></li>    
                    {% else %}
                    <li><a href="{% url 'common:login' %}">Login</a></li>    
                    {% endif %}
                </ul>
            </div>
        </nav>
          <ul class="sidenav" id="mobile-demo">
                <li><a href="{% url 'firstapp:index' %}">main</a></li>
                <li><a href="{% url 'firstapp:post_list' %}">Posts</a></li>
                <li><a href="{% url 'firstapp:view_stock' %}?sname=카카오">Stocks</a></li>
                <li><a href="{% url 'firstapp:lh_notice' %}">LH</a></li>
                {% if user.is_authenticated %}
                <!--li><a href="">Mypage</a></li-->
                <li><a href="{% url 'common:logout' %}?next={{ request.path }}">Logout</a></li>    
                {% else %}
                <li><a href="{% url 'common:login' %}">Login</a></li>    
                {% endif %}
          </ul>
        {% block content %}
        {% endblock %}
        </div>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                var elems = document.querySelectorAll('.sidenav');
                var instances = M.Sidenav.init(elems);
            });
        </script>
    </body>
</html>

firstapp/templates/firstapp/fileupload.html
{% extends 'firstapp/base.html' %}
{% block content %}
<div class="container">
    <form method="POST" action="{% url 'firstapp:fileupload' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ fileuploadForm }}
        <input type="submit" class="btn btn-primary col-12" value="제출">
    </form>
</div>
{% endblock%}

firstapp/templates/firstapp/index.html
{% extends 'firstapp/base.html' %}
{% load static %}
{% block content %}
        <center>
            <p>Hello There!</p>
            <img src="{% static 'ttabong.jpg' %}">
            <p>Nice!</p>
            <a href="{% url 'firstapp:post_list' %}">Enter</a>
        </center>
{% endblock %}

firstapp/templates/firstapp/index_old.html
<html>
    <head>
        <title>supy</title>
    </head>
    <body>
        <center>
            <p>Hello There!</p>
            <img src="https://proxy.goorm.io//service/6097d4a9c378c9ce36f8fb63_dJMhv3McZ8pwU3q8ftX.run.goorm.io/9080//file/load/ttabong.jpg?path=d29ya3NwYWNlJTJGc3VweSUyRmZpcnN0YXBwJTJGdGVtcGxhdGVzJTJGdHRhYm9uZy5qcGc=&docker_id=dJMhv3McZ8pwU3q8ftX&secure_session_id=tkTyxp0DlaxtLd8mIfgY6D2DYeebIHHj">
            <p>Nice!</p>
            <a href="">Enter</a>
        </center>
    </body>
</html>

firstapp/templates/firstapp/lh_notices.html
{% extends 'firstapp/base.html' %}
{% block content %}
        <center>
            <H1>행복주택 공고</H1>
        </center>
<div align="right">
    <form name="frm">
    <select class="browser-default" id="changeLoc" name="PAN_SS" onchange="document.frm.submit();">
        {% if not status %}
        <option value="" selected>전체</option>
        <option value="공고중">공고중</option>
        <option value="접수중">접수중</option>
        <option value="접수마감">접수마감</option>
        {% elif status == "공고중" %}
        <option value="">전체</option>
        <option value="공고중" selected>공고중</option>
        <option value="접수중">접수중</option>
        <option value="접수마감">접수마감</option>
        {% elif status == "접수중" %}
        <option value="">전체</option>
        <option value="공고중">공고중</option>
        <option value="접수중" selected>접수중</option>
        <option value="접수마감">접수마감</option>
        {% elif status == "접수마감" %}
        <option value="">전체</option>
        <option value="공고중">공고중</option>
        <option value="접수중">접수중</option>
        <option value="접수마감" selected>접수마감</option>
        
        {% endif %}
        
    </select>
    </form>
</div>
{% for notice in notices %}
        <a href="{{ notice.DTL_URL }}" target="blank">
            <div class='card-panel'>
                <p>상태: {{ notice.PAN_SS }}</p>
                <p>공고유형: {{ notice.UPP_AIS_TP_NM }}</p>
                <p>공고세부유형: {{ notice.AIS_TP_CD_NM }}</p>
                <p>공고명: {{ notice.PAN_NM }}</p>
                <p>지역: {{ notice.CNP_CD_NM }}</p>
            </div>
        </a>
{% empty %}
        <h2>데이터가 없습니다.</h2>
{% endfor %}
<script>
document.querySelector('#changeLoc').style.width="20%"
</script>
{% endblock %}

firstapp/templates/firstapp/post_detail.html
{% extends 'firstapp/base.html' %}
{% block content %}
<div>
    <p>created: {{ post.created_date }}</p>
    {% if post.modified_date %}
		<p>last modified: {{ post.modified_date }}</p>
    {% endif %}
    {% if request.user == post.author %}
    <a href="{% url 'firstapp:post_modify' post.id  %}" class="btn btn-sm btn-outline-secondary">수정</a>
    <button data-uri="{% url 'firstapp:post_delete' post.id  %}" class="btn btn-sm btn-outline-secondary delete">삭제</button>
    {% endif %}
    <h1>{{ post.title }}</h1>
    <p>{{ post.text|linebreaksbr }}</p>
</div>

<div class="fixed-action-btn">
  <a href="{% url 'firstapp:post_new' %}" class="btn-floating btn-large waves-effect waves-light red">
    <i class="large material-icons">mode_edit</i>
  </a>
</div>

<script type='text/javascript'>


$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>

{% endblock %}

firstapp/templates/firstapp/post_edit.html
{% extends 'firstapp/base.html' %}

{% block content %}
{% if edit == True %}
    <h1>글 수정</h1>
{% else %}
    <h1>새글</h1>
{% endif %}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

firstapp/templates/firstapp/post_list.html
{% extends 'firstapp/base.html' %}
{% block content %}
{% for post in posts %}
    <div class='card-panel'>
        <p>created: {{ post.created_date }}</p>
        <h1><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endfor %}
<center>
    <ul class="pagination">
        {% if posts.has_previous %}
        <li class="waves-effect"><a href="?page={{ posts.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
        {% else %}
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
        {% endif %}
        {% for page_number in posts.paginator.page_range %}
            {% if page_number >= posts.number|add:-5 and page_number <= posts.number|add:5 %}
                {% if page_number == posts.number %}                                                                                                     
                <li class="active"><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                {% else %}
                <li class="waves-effect"><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% if posts.has_next %}
        <li class="waves-effect"><a href="?page={{ posts.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
        {% else %}
        <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
        {% endif %}
    </ul>
    <!--form>
        <div class="input-field">
              <input id="search" type="search" required>
              <label class="label-icon" for="search"><i class="material-icons">search</i></label>
              <i class="material-icons">close</i>
            <a class="btn-floating btn-large red">
                <i class="large material-icons">mode_edit</i>
            </a>
        </div>

    </form-->
</center>
<div class="fixed-action-btn">
  <a href="{% url 'firstapp:post_new' %}" class="btn-floating btn-large waves-effect waves-light red">
    <i class="large material-icons">mode_edit</i>
  </a>
</div>
<script>
$("div.card-panel").css("cursor","pointer")
$("div.card-panel").on("click",function(){
    location.href=$(this).find("a").attr("href");
})
</script>
{% endblock %}

firstapp/templates/firstapp/view_stock.html
{% extends 'firstapp/base.html' %}
{% block content %}
        <center>
            <H1>Stocks</H1>
            <form>
                <div class="input-field">
                      <input id="search" type="search" name="sname" required>
                      <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                      <i class="material-icons">close</i>
                </div>
            </form>
        </center>

<div class='row'>
    {% for stock in stocks %}
    <div class='card-panel col s3'>
        <p>eltscYn: {{ stock.eltscYn }}</p>
        <p>영문 종목명: {{ stock.engSecnNm }}</p>
        <p>종목번호: {{ stock.isin }}</p>
        <p>발행일: {{ stock.issuDt }}</p>
        <p>발행회사번호: {{ stock.issucoCustno }}</p>
        <p>국문종목명: {{ stock.korSecnNm }}</p>
        <p>주식종류: {{ stock.secnKacdNm }}</p>
    </div>
    {% empty %}
    <h2>데이터가 없습니다.</h2>
    {% endfor %}
</div>

{% endblock %}

firstapp/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}